{{- if (.Values.userService.enabled) -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.userService.name }}
  labels:
    app: {{ .Values.userService.name }}
    ctx: {{ .Chart.Name }}
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: {{ .Values.userService.name }}

{{- end }}
