name: CI pipeline

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0

      - name: Set up path
        run: |
          mkdir -p $HOME/.local
          mkdir -p $HOME/.local/bin
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run k8s cluster with tests
        run: |
          cp .env.dist .env
          make kind-up tilt-ci

      - name: Clean k8s cluster
        if: always()
        run: |
          (make kind-down) || true
